name: Java CI with Gradle and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload build jar file
      uses: actions/upload-artifact@v2
      with:
        name: build jar file
        path: ./build/libs/BDDWithCucumber.jar
    - name: Run Cucumber Test
      run: ./gradlew cucumber
    - name: Run build
      run: ./gradlew build
    - name: Run analysis for code quality
      run: ./gradlew sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Run build
      run: ./gradlew dockerPushDockerHub
